### ISSUE TITLE
Plans cleanup (personal tracking issue, please open at upstream)

### ISSUE THREAD

**Issue by rsertelon** [rsertelon/core-plans#1]
- [ ] 7zip
- [ ] ant -> JAVA_HOME could be used from jdk
- [ ] aws-cli
- [ ] bash
- [ ] bash-static
- [ ] binutils
- [x] acbuild
- [x] acl -> PR pending
- [x] apr
- [x] apr-util
- [x] aspcud
- [x] atk
- [x] attr
- [x] at-spi2-atk
- [x] at-spi2-core
- [x] autoconf
- [x] autogen
- [x] automake
- [x] bash-completion
- [x] bats
- [x] bc
- [x] bdwgc
- [x] bin
- [x] bison
- [x] bison2
- [ ] boost
- [ ] bundler
- [ ] busybox
- [ ] busybox-static
- [ ] bzip2
- [ ] bzip2-musl
- [ ] cacerts
- [ ] caddy
- [ ] cairo
- [ ] camlp4
- [ ] c-ares
- [ ] cargo-nightly
- [ ] ccache
- [ ] certstrap
- [x] check
- [ ] clens
- [ ] clingo
- [ ] cmake
- [ ] composer
- [ ] concourse
- [ ] consul
- [ ] coreutils
- [ ] coreutils-static
- [ ] cpanminus
- [ ] cpio
- [ ] cppunit
- [ ] cpputest
- [ ] curator
- [ ] curl
- [ ] curl-static-musl
- [ ] cyrus-sasl
- [x] damageproto
- [ ] db
- [ ] dbus
- [ ] dd-agent
- [x] dejagnu
- [ ] dep
- [ ] devicemapper
- [ ] dex
- [ ] diffutils
- [ ] direnv
- [ ] docker
- [ ] docker-credential-helper
- [ ] docutils
- [ ] dosfstools
- [ ] dotnet-47-dev-pack
- [ ] dotnet-core
- [ ] dotnet-core-lts
- [ ] dotnet-core-sdk
- [ ] dotnet-core-sdk-lts
- [ ] dotnet-core-sdk-preview
- [ ] doxygen
- [ ] dpkg
- [x] dri2proto
- [ ] drupal
- [ ] drush
- [ ] e2fsprogs
- [ ] ed
- [ ] elasticsearch
- [ ] elfutils
- [ ] elixir
- [ ] envdir
- [ ] erlang
- [ ] erlang16
- [ ] erlang18
- [ ] erlang19
- [ ] etcd
- [ ] eudev
- [ ] expat
- [x] expect
- [ ] ffmpeg
- [ ] file
- [ ] findutils
- [ ] fish
- [x] fixesproto
- [ ] flatbuffers
- [ ] flex
- [ ] fontconfig
- [ ] foulkon
- [ ] fping
- [ ] freetype
- [ ] galera
- [ ] gamin
- [ ] gawk
- [ ] gcc
- [ ] gcc-libs
- [ ] gdal
- [ ] gdb
- [ ] gdbm
- [ ] gdk-pixbuf
- [ ] gecode
- [ ] geoip
- [ ] geos
- [ ] gettext
- [ ] giflib
- [ ] gifsicle
- [ ] git
- [x] glib
- [ ] glibc
- [ ] glproto
- [ ] gmp
- [ ] gnatsd
- [ ] gnupg
- [ ] gnupg-static
- [ ] go
- [ ] go14
- [ ] go17
- [ ] goreplay
- [ ] gox
- [ ] gperf
- [ ] gpgme
- [ ] gradle
- [ ] grafana
- [ ] graphviz
- [ ] grep
- [ ] groff
- [ ] grub
- [ ] gsl
- [ ] gtk2
- [ ] guile
- [ ] gzip
- [ ] handlebars-cmd
- [ ] haproxy
- [ ] harfbuzz
- [ ] htop
- [ ] httpd
- [ ] iana-etc
- [ ] icu
- [ ] icu52
- [ ] icu56
- [ ] imagemagick
- [ ] inetutils
- [ ] innounp
- [ ] inotify-tools
- [x] inputproto
- [ ] intltool
- [ ] iproute2
- [ ] iptables
- [ ] jbigkit
- [ ] jdk7
- [ ] jdk8
- [ ] jdk9
- [ ] jemalloc
- [ ] jenkins
- [ ] jetty
- [ ] jffi
- [ ] jfrog-cli
- [ ] jo
- [ ] jq-static
- [ ] jre7
- [ ] jre8
- [ ] jre9
- [ ] jruby
- [ ] jruby1
- [ ] json-glib
- [ ] kafka
- [x] kbproto
- [ ] kibana
- [ ] kmod
- [ ] krb5
- [ ] kubernetes
- [ ] kubernetes-apiserver
- [ ] kubernetes-controller-manager
- [ ] kubernetes-kubelet
- [ ] kubernetes-proxy
- [ ] kubernetes-scheduler
- [ ] lcms2
- [ ] less
- [ ] lessmsi
- [ ] leveldb
- [ ] libaio
- [ ] libarchive
- [ ] libarchive-musl
- [ ] libassuan
- [ ] libatomic_ops
- [x] libbsd
- [ ] libcap
- [ ] libcap-ng
- [ ] libcxx
- [ ] libdrm
- [ ] libedit
- [ ] liberation-fonts-ttf
- [ ] libev
- [ ] libevent
- [ ] libffi
- [ ] libgcrypt
- [ ] libghthash
- [ ] libgpg-error
- [ ] libice
- [ ] libiconv
- [x] libidn
- [ ] libjpeg-turbo
- [ ] libksba
- [ ] libmpc
- [ ] libossp-uuid
- [ ] libpcap
- [ ] libpciaccess
- [ ] libpipeline
- [ ] libpng
- [ ] libpthread-stubs
- [ ] libressl
- [ ] libressl-musl
- [ ] libscrypt
- [ ] libseccomp
- [ ] libsm
- [ ] libsodium
- [ ] libsodium-musl
- [ ] libtermkey
- [ ] libtiff
- [ ] libtool
- [ ] libunistring
- [ ] libunwind
- [ ] libuv
- [ ] libvterm
- [ ] libwebp
- [ ] libxau
- [ ] libxcb
- [ ] libxdamage
- [ ] libxdmcp
- [ ] libxext
- [ ] libxfixes
- [ ] libxi
- [ ] libxml2
- [ ] libxmu
- [ ] libxrandr
- [ ] libxrender
- [ ] libxshmfence
- [ ] libxslt
- [ ] libxt
- [ ] libxtst
- [ ] libyajl2
- [ ] libyaml
- [ ] linux
- [ ] linux-headers
- [x] linux-headers-musl
- [ ] linux-pam
- [ ] llvm
- [ ] local-lib
- [ ] logback
- [ ] logstash
- [ ] logstash2
- [ ] lsof
- [ ] lsyncd
- [ ] lttng-ust
- [ ] lua
- [ ] lynx
- [ ] lz4
- [ ] lzip
- [ ] lzo
- [ ] lzop
- [ ] m4
- [ ] make
- [ ] man-db
- [ ] man-pages
- [ ] mariadb
- [ ] maven
- [ ] mawk
- [ ] mc
- [ ] memcached
- [ ] mention-bot
- [ ] mercurial
- [ ] meson
- [ ] mg
- [ ] mongodb
- [ ] mongo-tools
- [ ] monit
- [ ] mosquitto
- [ ] mpfr
- [ ] msgpack
- [ ] mssql
- [x] musl
- [ ] mysql
- [ ] mysql-client
- [ ] nasm
- [ ] nats-streaming-server
- [ ] nats-top
- [ ] ncdu
- [ ] ncurses
- [ ] netcat
- [ ] netcat-openbsd
- [ ] net-tools
- [ ] nghttp2
- [ ] nginx
- [ ] ninja
- [ ] nmap
- [ ] node
- [ ] node6
- [ ] node9
- [ ] node_exporter
- [ ] npth
- [ ] nspr
- [ ] nss
- [ ] nuget
- [ ] numactl
- [ ] ocaml
- [ ] ocamlbuild
- [ ] omniORB
- [ ] opam
- [ ] openjpeg
- [ ] openldap
- [ ] openresty
- [ ] openssh
- [ ] openssl
- [ ] openssl-musl
- [ ] openvpn
- [ ] packer
- [ ] pango
- [ ] papi
- [ ] patch
- [ ] patchelf
- [ ] pax-utils
- [ ] pcre
- [ ] percona-xtrabackup
- [ ] perl
- [ ] phantomjs
- [ ] php
- [ ] php5
- [ ] pixman
- [ ] pkg-config
- [ ] polipo
- [ ] ponysay
- [ ] popt
- [ ] postgresql
- [ ] postgresql93
- [ ] postgresql94
- [ ] postgresql95
- [ ] powershell
- [ ] procps-ng
- [ ] proj
- [ ] prometheus
- [ ] protobuf
- [ ] protobuf-c
- [ ] protobuf-cpp
- [ ] protobuf-rust
- [ ] psmisc
- [ ] pv
- [ ] python
- [ ] python2
- [ ] qemu
- [ ] R
- [ ] rabbitmq
- [ ] rabbitmqadmin
- [ ] raml2html
- [x] randrproto
- [ ] re2c
- [ ] readline
- [ ] rebar3
- [x] recordproto
- [ ] redis
- [ ] relx
- [x] renderproto
- [ ] repo
- [ ] results
- [ ] rethinkdb
- [ ] rngd
- [ ] rpm
- [ ] rq
- [ ] rsync
- [ ] ruby
- [ ] runit
- [ ] rust
- [ ] rust-nightly
- [ ] sassc
- [ ] scaffolding-base
- [ ] scaffolding-go
- [ ] scaffolding-go17
- [ ] scaffolding-gradle
- [ ] scaffolding-node
- [ ] scaffolding-ruby
- [ ] scons
- [ ] sed
- [ ] sensu
- [ ] serf
- [ ] shadow
- [ ] shared-mime-info
- [ ] shield
- [ ] shield-agent
- [ ] shield-proxy
- [ ] snappy
- [ ] socat
- [ ] spark
- [ ] sqitch
- [ ] sqlite
- [ ] storm
- [ ] strace
- [ ] stringencoders
- [ ] subversion
- [ ] sudo
- [ ] sumologic
- [ ] swig
- [ ] sysstat
- [ ] systemd
- [ ] tar
- [ ] tcl
- [ ] tcpdump
- [ ] telegraf
- [ ] terraform
- [ ] texinfo
- [ ] tmux
- [ ] tomcat7
- [ ] tomcat8
- [ ] tomcat-native
- [ ] tor
- [ ] traefik
- [ ] tree
- [ ] ttyrec
- [ ] tzdata
- [ ] unibilium
- [x] unzip
- [ ] userspace-rcu
- [ ] util-linux
- [ ] util-macros
- [ ] valgrind
- [ ] varnish
- [ ] vault
- [ ] vde2
- [x] vim
- [ ] virtualenv
- [ ] visual-cpp-build-tools-2015
- [ ] visual-cpp-redist-2013
- [ ] vmtouch
- [ ] wal-e
- [x] wget
- [ ] wget-static
- [ ] which
- [ ] wix
- [ ] wordpress
- [ ] wordpress-proxy
- [ ] wrk
- [x] xcb-proto
- [x] xextproto
- [ ] xeyes
- [ ] xlib
- [x] xproto
- [ ] xtrans
- [ ] xz
- [ ] xz-musl
- [ ] yarn
- [ ] yasm
- [ ] zeromq
- [ ] zip
- [ ] zlib
- [ ] zlib-musl
- [ ] zookeeper
- [ ] zsh
- [ ] zstd
